module.exports = {
  apps: [
    {
      name: 'Jarvis',
      script: 'jarvis-telegram.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'gmail-watcher',
      script: 'gmail-watcher.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'alpha-scraper',
      script: 'alpha-scraper.js',
      cron_restart: '*/30 * * * *',
      autorestart: false,
      watch: false,
    },
    {
      name: 'call-analyzer',
      script: 'call-analyzer.js',
      args: '--batch',
      cron_restart: '0 * * * *',
      autorestart: false,
      watch: false,
    },
    {
      name: 'county-scraper',
      script: 'county-scraper.js',
      cron_restart: '0 7 * * *',
      autorestart: false,
      watch: false,
    },
    {
      name: 'jarvis-caller',
      script: 'jarvis-caller.js',
      autorestart: true,   // daemon mode — stays alive, schedules calls via internal cron
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'mortgage-backfill',
      script: 'scripts/backfill-mortgage.js',
      instances: 1,
      autorestart: false,
      watch: false,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'qa-tester',
      script: '/Users/chrislovera/v0-asap-arv-tool/scripts/qa-tester.js',
      instances: 1,
      cron_restart: '0 * * * *',
      autorestart: false,
      watch: false,
    },
        {
      name: 'chris-coach',
      script: 'chris-coach.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'chris-accountability',
      script: 'chris-accountability.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'marketing-intel',
      script: 'marketing-intel.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'jarvis-watchdog',
      script: 'jarvis-watchdog.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'call-coach',
      script: 'call-coach.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'scout',
      script: 'scout-agent.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'felix',
      script: 'felix-agent.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'aria',
      script: 'aria-agent.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'max',
      script: 'max-agent.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'penny',
      script: 'penny-agent.js',
      autorestart: true,
      watch: false,
    },
    {
      name: 'sage',
      script: 'sage-agent.js',
      autorestart: true,
      watch: false,
    },
    { name: 'asap-worker-1', script: 'asap-scraper.js', args: '--worker 1', autorestart: true, watch: false },
    { name: 'asap-worker-2', script: 'asap-scraper.js', args: '--worker 2', autorestart: true, watch: false },
    { name: 'asap-worker-3', script: 'asap-scraper.js', args: '--worker 3', autorestart: true, watch: false },
    { name: 'asap-worker-4', script: 'asap-scraper.js', args: '--worker 4', autorestart: true, watch: false },
    { name: 'asap-worker-5', script: 'asap-scraper.js', args: '--worker 5', autorestart: true, watch: false },
    { name: 'asap-worker-6', script: 'asap-scraper.js', args: '--worker 6', autorestart: true, watch: false },
    { name: 'asap-worker-7', script: 'asap-scraper.js', args: '--worker 7', autorestart: true, watch: false },
    { name: 'asap-worker-8', script: 'asap-scraper.js', args: '--worker 8', autorestart: true, watch: false },
  ],
}
